version: '3.7'

services: 
  db:
    image: mysql:5.6
    volumes: 
      - data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: pruebaroot
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp12345
  web:
    image: wordpress:5-php7.2-apache
    ports: 
      - "8080:80"
    depends_on: 
      - db
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp12345
      WORDPRESS_DB_NAME: db_wordpress
  dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports: 
      - "8081:80"
    depends_on: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: pruebaroot

volumes: 
  data: